# Generated by Django 4.1.7 on 2023-02-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='content',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='notifications',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='notifications',
            name='poster',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
