# Generated by Django 4.1.7 on 2023-02-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_notifications_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='poster',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
