# Generated by Django 4.1.7 on 2023-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_notifications_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=400)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('content', models.CharField(blank=True, max_length=4000)),
                ('description', models.CharField(blank=True, max_length=4000)),
                ('urlToImage', models.ImageField(default='', upload_to='images')),
                ('source', models.CharField(blank=True, max_length=400)),
                ('publishedAt', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
