# Generated by Django 4.1.7 on 2023-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='urlToImage',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
