# Generated by Django 4.1.7 on 2023-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_news_urltoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='urlToImage',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
